title: Guilherme Bail
email: guilhermedanbail@gmail.com
description: >-
    portfolio && blog
baseurl: ""
url: "https://bail.dev"
github_username: wbail
linkedin_username: guilherme-bail
medium_username: \@wbail

show_excerpts: true

defaults:
  -
    scope:
      path: "_posts"
    values:
      permalink: "/:categories/:title"

markdown: kramdown
#theme: no-style-please
remote_theme: riggraz/no-style-please
favicon: favicon.ico

theme_config:
    back_home_text: "...back"
    show_description: true

plugins:
  - jekyll-feed

feed:
  categories:
    - portfolio
    - blog
